#### Topics
- asarray()
- asanyarray()
- matrix()
- deepcopy and shallow copy
- fromfunction()
- fromiter()
- fromstring()
- ndim
- size
- shape
- dtypes
- arange
- linspace()
- zeros()
- ones()
- empty()
- eye()
- logspace()
- random.randn()
- random.rand()
- random.randint()
- reshape()
- array assignment, slicing, arithmetic operations
- matrix multiplication arr1@arr2
- broadcasting
- sqrt()  , exp()    , log()

In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5,8]
n = np.array(l)

In [4]:
n

array([1, 2, 3, 4, 5, 8])

In [5]:
type(n)

numpy.ndarray

In [6]:
np.array([[1,2],[2,3]])

array([[1, 2],
       [2, 3]])

In [7]:
#### asarray()

In [8]:
np.asarray(l)

array([1, 2, 3, 4, 5, 8])

In [9]:
#### asanyarray()

In [10]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 8])

##### matrix always returns 2d data 

In [11]:
a = np.matrix(l)

In [12]:
#### asanyarray will not change the matrix into array because matrix is a subclass of array

In [13]:
np.asanyarray(a)

matrix([[1, 2, 3, 4, 5, 8]])

#### shallow copy
copied file will share the same memory location

In [18]:
a = np.array([1,2,3,4,5,6])

In [21]:
c = a

In [22]:
a[0] = 100

In [25]:
a

array([100,   2,   3,   4,   5,   6])

In [24]:
c

array([100,   2,   3,   4,   5,   6])

#### Deep copy
copied file will not share the same location

In [26]:
## copy b from 
b = np.array(a)

In [27]:
a[1] = 400

In [28]:
## no change in b
b

array([100,   2,   3,   4,   5,   6])

#####  fromfunction()     ,  fromiter()   , fromstring()
funtion to generate different dimesndhions of array

In [29]:
np.fromfunction(lambda i, j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
iterable = (i*i for i in range (5))

In [36]:
np.fromiter(iterable,float )

array([ 0.,  1.,  4.,  9., 16.])

In [38]:
np.fromstring("124 245",sep= ' ' )

array([124., 245.])

In [39]:
np.fromstring("124,878" , sep = ",")

array([124., 878.])

In [40]:
#Numpy data types

In [49]:
ar = np.array([1,2,3,4,5,6])

In [50]:
ar.ndim

1

#### shape

In [51]:
ar.shape

(6,)

#### size

In [52]:
ar.size

6

In [44]:
ar = np.array([[1,2,3,4,5,6],[1,2,3,45,6,4]])

In [45]:
ar.ndim

2

In [46]:
ar.size

12

In [47]:
ar.shape

(2, 6)

#### dtype

In [55]:
ar.dtype

dtype('int64')

In [59]:
ar22 = np.array([(1.4,85,25),(1,25,8)])

In [60]:
ar22

array([[ 1.4, 85. , 25. ],
       [ 1. , 25. ,  8. ]])

In [61]:
## because of one floating value it is converting the dtype into float
ar22.dtype

dtype('float64')

In [ ]:
# arange()

In [62]:
list(range(5))

[0, 1, 2, 3, 4]

In [63]:
## start,stop
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [64]:
## start , stop, step
np.arange(2.1,10.1,2)

array([2.1, 4.1, 6.1, 8.1])

In [65]:
list(np.arange(1,4,0.8))

[1.0, 1.8, 2.6, 3.4000000000000004]

#### linespace()

In [68]:
## generates data in a range and we can specify the number of data needed in between the range
np.linspace(1.5,2.5,10)

array([1.5       , 1.61111111, 1.72222222, 1.83333333, 1.94444444,
       2.05555556, 2.16666667, 2.27777778, 2.38888889, 2.5       ])

In [69]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [71]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### ones()

In [83]:
on = np.ones((2,3))

In [84]:
(on) + 5

array([[6., 6., 6.],
       [6., 6., 6.]])

In [85]:
on * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [76]:
## number of matrix,rows,colum
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

#### 4D array

In [80]:
four_D = np.ones((2,4,2,3))

In [81]:
four_D.ndim

4

#### empty()
 it generates values that are negligible

In [89]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

#### identity matrix using eye() function

In [98]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [102]:
np.linspace(2,4,12)

array([2.        , 2.18181818, 2.36363636, 2.54545455, 2.72727273,
       2.90909091, 3.09090909, 3.27272727, 3.45454545, 3.63636364,
       3.81818182, 4.        ])

In [108]:

np.logspace(4,5,15, base = 2)

array([16.        , 16.81210622, 17.66543222, 18.56207018, 19.50421847,
       20.49418704, 21.53440308, 22.627417  , 23.77590863, 24.98269383,
       26.25073139, 27.58313028, 28.98315726, 30.4542449 , 32.        ])

##### random.randn()   random.rand()

##### random.randint()

In [110]:
### it uses standard normal distribution
## data generated by this will have mean = 0 std = 1
arr = np.random.randn(3,4)

In [114]:
import pandas as pd
pd.DataFrame(arr)

0         1         2         3
0  0.632519 -0.145429  0.746485  0.108037
1 -0.119431 -0.762917 -0.423926  0.242731
2  1.184909  1.553525  2.220753  0.009492

In [118]:
np.random.rand(4,2)

array([[0.17379709, 0.25134355],
       [0.65965607, 0.16153184],
       [0.90466226, 0.34295079],
       [0.9930519 , 0.67872638]])

In [122]:
## (range,(r*w))
np.random.randint(3,101,(3,4))

array([[81, 88, 19, 62],
       [99, 21, 83, 66],
       [73, 53, 69, 90]])

#### reshape()

In [24]:
bar = np.random.rand(3,4)

In [25]:
b = bar.reshape(6,2)
b

array([[0.77717842, 0.69745985],
       [0.23120662, 0.66014983],
       [0.68684499, 0.47527265],
       [0.60517675, 0.59822074],
       [0.10203118, 0.36349072],
       [0.05592911, 0.05687428]])

In [26]:
## row column
b[0][1]

0.697459845267353

In [27]:
## rowstart:end , columns
b[2:5,[1]]

array([[0.47527265],
       [0.59822074],
       [0.36349072]])

In [162]:
b[2:5,1]

array([0.82588167, 0.6628639 , 0.43251767])

In [ ]:
#### Condtion

In [6]:
import numpy as np
arr = np.random.randint(1,100,(5,5))

In [9]:
## condition
arr[arr>50]

array([96, 79, 80, 92, 86, 57, 84, 63, 94, 98, 98, 93, 80, 66, 57, 76, 86])

In [10]:
arr

array([[96, 79, 80, 92, 86],
       [57, 84, 63, 14, 47],
       [94, 98, 34, 98, 39],
       [93, 80, 66, 14, 57],
       [50,  6, 76, 29, 86]])

In [21]:
arr[2:4,[1,3]]

array([[98, 98],
       [80, 14]])

### manupulation data, arithmetical operationss

In [28]:

arr[0][0] = 100 

In [30]:
arr

array([[100,  79,  80,  92,  86],
       [ 57,  84,  63,  14,  47],
       [ 94,  98,  34,  98,  39],
       [ 93,  80,  66,  14,  57],
       [ 50,   6,  76,  29,  86]])

In [36]:
arr1 = np.random.randint(1,10,(3,3))

In [39]:
arr1

array([[9, 5, 1],
       [9, 6, 9],
       [5, 9, 4]])

In [37]:
arr2 = np.random.randint(1,10,(3,3))

In [40]:
arr2

array([[8, 6, 6],
       [3, 2, 7],
       [4, 4, 6]])

In [38]:
arr1 + arr2

array([[17, 11,  7],
       [12,  8, 16],
       [ 9, 13, 10]])

In [41]:
arr1 - arr2

array([[ 1, -1, -5],
       [ 6,  4,  2],
       [ 1,  5, -2]])

In [43]:
arr1 / arr2

array([[1.125     , 0.83333333, 0.16666667],
       [3.        , 3.        , 1.28571429],
       [1.25      , 2.25      , 0.66666667]])

In [44]:
## simple index wise multiplication
arr1 * arr2 

array([[72, 30,  6],
       [27, 12, 63],
       [20, 36, 24]])

#### matrix multiplication

In [45]:
arr1@arr2

array([[ 91,  68,  95],
       [126, 102, 150],
       [ 83,  64, 117]])

In [46]:
arr1 / 0 

/tmp/ipykernel_2356/1950694141.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [47]:
arr1 + 100

array([[109, 105, 101],
       [109, 106, 109],
       [105, 109, 104]])

In [48]:
arr1 ** 2

array([[81, 25,  1],
       [81, 36, 81],
       [25, 81, 16]])

#### broadcasting
it means adding the data row wise

In [49]:
ar = np.zeros((4,4))

In [50]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
row = np.array([1,2,3,4])

In [52]:
row

array([1, 2, 3, 4])

In [53]:
ar + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [57]:
## one dimensional array cannot be transposed
row.T

array([1, 2, 3, 4])

In [64]:
## passid the data inside list
col =  np.array([[1,2,3,4]])

In [65]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [66]:
col.shape

(1, 4)

In [67]:
ar + col

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [69]:
ar1 = np.random.randint(1,4,(3,4))

In [70]:
ar1

array([[2, 1, 2, 2],
       [3, 3, 3, 1],
       [1, 3, 1, 1]])

In [71]:
np.sqrt(ar1)

array([[1.41421356, 1.        , 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081, 1.        ],
       [1.        , 1.73205081, 1.        , 1.        ]])

In [72]:
np.exp(ar1)

array([[ 7.3890561 ,  2.71828183,  7.3890561 ,  7.3890561 ],
       [20.08553692, 20.08553692, 20.08553692,  2.71828183],
       [ 2.71828183, 20.08553692,  2.71828183,  2.71828183]])

In [74]:
np.log10(arr1)

array([[0.95424251, 0.69897   , 0.        ],
       [0.95424251, 0.77815125, 0.95424251],
       [0.69897   , 0.95424251, 0.60205999]])